# Generated by Django 4.2.7 on 2025-06-21 22:56

import apps.translations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttranslation',
            name='original_document',
            field=models.FileField(upload_to=apps.translations.models.document_original_path),
        ),
        migrations.AlterField(
            model_name='documenttranslation',
            name='translated_document',
            field=models.FileField(blank=True, null=True, upload_to=apps.translations.models.document_translated_path),
        ),
    ]
